//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class Cargo : XPLiteObject
    {
        int fIdCargo;
        [Key(true)]
        [Persistent(@"idCargo")]
        public int IdCargo
        {
            get { return fIdCargo; }
            set { SetPropertyValue<int>(nameof(IdCargo), ref fIdCargo, value); }
        }
        string fNombre;
        [Size(50)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDescripcion;
        [Size(120)]
        [Persistent(@"descripcion")]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        [Association(@"EmpleadoReferencesCargo")]
        public XPCollection<Empleado> Empleadoes { get { return GetCollection<Empleado>(nameof(Empleadoes)); } }
    }

}
