//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class Cliente : XPLiteObject
    {
        int fIdCliente;
        [Key(true)]
        [Persistent(@"idCliente")]
        public int IdCliente
        {
            get { return fIdCliente; }
            set { SetPropertyValue<int>(nameof(IdCliente), ref fIdCliente, value); }
        }
        string fNombre;
        [Size(60)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fApellido;
        [Size(60)]
        [Persistent(@"apellido")]
        public string Apellido
        {
            get { return fApellido; }
            set { SetPropertyValue<string>(nameof(Apellido), ref fApellido, value); }
        }
        char fSexo;
        [Persistent(@"sexo")]
        public char Sexo
        {
            get { return fSexo; }
            set { SetPropertyValue<char>(nameof(Sexo), ref fSexo, value); }
        }
        string fDireccion;
        [Size(200)]
        [Persistent(@"direccion")]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fCedula;
        [Size(18)]
        [Persistent(@"cedula")]
        public string Cedula
        {
            get { return fCedula; }
            set { SetPropertyValue<string>(nameof(Cedula), ref fCedula, value); }
        }
        string fTelefono;
        [Size(20)]
        [Persistent(@"telefono")]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        DateTime fFechaRegistro;
        [Persistent(@"fechaRegistro")]
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        Estado fIdEstado;
        [Persistent(@"idEstado")]
        [Association(@"ClienteReferencesEstado")]
        public Estado IdEstado
        {
            get { return fIdEstado; }
            set { SetPropertyValue<Estado>(nameof(IdEstado), ref fIdEstado, value); }
        }
        [Association(@"VentaReferencesCliente")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
