//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class DetalleVenta : XPLiteObject
    {
        int fIdDetalle;
        [Key(true)]
        [Persistent(@"idDetalle")]
        public int IdDetalle
        {
            get { return fIdDetalle; }
            set { SetPropertyValue<int>(nameof(IdDetalle), ref fIdDetalle, value); }
        }
        int fCantidad;
        [Persistent(@"cantidad")]
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        double fSubTotal;
        [Persistent(@"subTotal")]
        public double SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<double>(nameof(SubTotal), ref fSubTotal, value); }
        }
        Venta fIdVenta;
        [Persistent(@"idVenta")]
        [Association(@"DetalleVentaReferencesVenta")]
        public Venta IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<Venta>(nameof(IdVenta), ref fIdVenta, value); }
        }
        Producto fIdProducto;
        [Persistent(@"idProducto")]
        [Association(@"DetalleVentaReferencesProducto")]
        public Producto IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<Producto>(nameof(IdProducto), ref fIdProducto, value); }
        }
    }

}
