//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class Empleado : XPLiteObject
    {
        int fIdEmpleado;
        [Key(true)]
        [Persistent(@"idEmpleado")]
        public int IdEmpleado
        {
            get { return fIdEmpleado; }
            set { SetPropertyValue<int>(nameof(IdEmpleado), ref fIdEmpleado, value); }
        }
        string fNombres;
        [Size(60)]
        [Persistent(@"nombres")]
        public string Nombres
        {
            get { return fNombres; }
            set { SetPropertyValue<string>(nameof(Nombres), ref fNombres, value); }
        }
        string fApellidos;
        [Size(60)]
        [Persistent(@"apellidos")]
        public string Apellidos
        {
            get { return fApellidos; }
            set { SetPropertyValue<string>(nameof(Apellidos), ref fApellidos, value); }
        }
        char fSexo;
        [Persistent(@"sexo")]
        public char Sexo
        {
            get { return fSexo; }
            set { SetPropertyValue<char>(nameof(Sexo), ref fSexo, value); }
        }
        DateTime fFechaNacimiento;
        [Persistent(@"fechaNacimiento")]
        public DateTime FechaNacimiento
        {
            get { return fFechaNacimiento; }
            set { SetPropertyValue<DateTime>(nameof(FechaNacimiento), ref fFechaNacimiento, value); }
        }
        string fCedula;
        [Size(16)]
        [Persistent(@"cedula")]
        public string Cedula
        {
            get { return fCedula; }
            set { SetPropertyValue<string>(nameof(Cedula), ref fCedula, value); }
        }
        string fDireccion;
        [Size(200)]
        [Persistent(@"direccion")]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fTelefono;
        [Size(20)]
        [Persistent(@"telefono")]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        DateTime fFechaRegistro;
        [Persistent(@"fechaRegistro")]
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        Cargo fIdCargo;
        [Persistent(@"idCargo")]
        [Association(@"EmpleadoReferencesCargo")]
        public Cargo IdCargo
        {
            get { return fIdCargo; }
            set { SetPropertyValue<Cargo>(nameof(IdCargo), ref fIdCargo, value); }
        }
        Estado fIdEstado;
        [Persistent(@"idEstado")]
        [Association(@"EmpleadoReferencesEstado")]
        public Estado IdEstado
        {
            get { return fIdEstado; }
            set { SetPropertyValue<Estado>(nameof(IdEstado), ref fIdEstado, value); }
        }
        [Association(@"UsuarioReferencesEmpleado")]
        public XPCollection<Usuario> Usuarios { get { return GetCollection<Usuario>(nameof(Usuarios)); } }
    }

}
