//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class Producto : XPLiteObject
    {
        int fIdProducto;
        [Key(true)]
        [Persistent(@"idProducto")]
        public int IdProducto
        {
            get { return fIdProducto; }
            set { SetPropertyValue<int>(nameof(IdProducto), ref fIdProducto, value); }
        }
        string fNombre;
        [Size(60)]
        [Persistent(@"nombre")]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        double fPrecioUnidad;
        [Persistent(@"precioUnidad")]
        public double PrecioUnidad
        {
            get { return fPrecioUnidad; }
            set { SetPropertyValue<double>(nameof(PrecioUnidad), ref fPrecioUnidad, value); }
        }
        int fExistencias;
        [Persistent(@"existencias")]
        public int Existencias
        {
            get { return fExistencias; }
            set { SetPropertyValue<int>(nameof(Existencias), ref fExistencias, value); }
        }
        DateTime fFechaRegistro;
        [Persistent(@"fechaRegistro")]
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        Categoria fIdCategoria;
        [Persistent(@"idCategoria")]
        [Association(@"ProductoReferencesCategoria")]
        public Categoria IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<Categoria>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        Presentacion fIdPresentacion;
        [Persistent(@"idPresentacion")]
        [Association(@"ProductoReferencesPresentacion")]
        public Presentacion IdPresentacion
        {
            get { return fIdPresentacion; }
            set { SetPropertyValue<Presentacion>(nameof(IdPresentacion), ref fIdPresentacion, value); }
        }
        Estado fIdEstado;
        [Persistent(@"idEstado")]
        [Association(@"ProductoReferencesEstado")]
        public Estado IdEstado
        {
            get { return fIdEstado; }
            set { SetPropertyValue<Estado>(nameof(IdEstado), ref fIdEstado, value); }
        }
        [Association(@"DetalleEntradaReferencesProducto")]
        public XPCollection<DetalleEntrada> DetalleEntradas { get { return GetCollection<DetalleEntrada>(nameof(DetalleEntradas)); } }
        [Association(@"DetalleVentaReferencesProducto")]
        public XPCollection<DetalleVenta> DetalleVentas { get { return GetCollection<DetalleVenta>(nameof(DetalleVentas)); } }
    }

}
