//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class Usuario : XPLiteObject
    {
        int fIdUsuario;
        [Key(true)]
        [Persistent(@"idUsuario")]
        public int IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<int>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        string fLogin;
        [Size(8)]
        [Persistent(@"login")]
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>(nameof(Login), ref fLogin, value); }
        }
        string fClave;
        [Size(120)]
        [Persistent(@"clave")]
        public string Clave
        {
            get { return fClave; }
            set { SetPropertyValue<string>(nameof(Clave), ref fClave, value); }
        }
        DateTime fFechaRegistro;
        [Persistent(@"fechaRegistro")]
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        Empleado fIdEmpleado;
        [Persistent(@"idEmpleado")]
        [Association(@"UsuarioReferencesEmpleado")]
        public Empleado IdEmpleado
        {
            get { return fIdEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(IdEmpleado), ref fIdEmpleado, value); }
        }
    }

}
