//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class Usuario : XPLiteObject
    {
        int fIdUsuario;
        [Key(true)]
        [Persistent(@"idUsuario")]
        public int IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<int>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        string fNombres;
        [Size(60)]
        [Persistent(@"nombres")]
        public string Nombres
        {
            get { return fNombres; }
            set { SetPropertyValue<string>(nameof(Nombres), ref fNombres, value); }
        }
        string fApellidos;
        [Size(60)]
        [Persistent(@"apellidos")]
        public string Apellidos
        {
            get { return fApellidos; }
            set { SetPropertyValue<string>(nameof(Apellidos), ref fApellidos, value); }
        }
        string fLogin;
        [Size(12)]
        [Persistent(@"login")]
        public string Login
        {
            get { return fLogin; }
            set { SetPropertyValue<string>(nameof(Login), ref fLogin, value); }
        }
        string fClave;
        [Size(120)]
        [Persistent(@"clave")]
        public string Clave
        {
            get { return fClave; }
            set { SetPropertyValue<string>(nameof(Clave), ref fClave, value); }
        }
        DateTime fFechaRegistro;
        [Persistent(@"fechaRegistro")]
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        Rol fIdRol;
        [Persistent(@"idRol")]
        [Association(@"UsuarioReferencesRol")]
        public Rol IdRol
        {
            get { return fIdRol; }
            set { SetPropertyValue<Rol>(nameof(IdRol), ref fIdRol, value); }
        }
        Estado fIdEstado;
        [Persistent(@"idEstado")]
        [Association(@"UsuarioReferencesEstado")]
        public Estado IdEstado
        {
            get { return fIdEstado; }
            set { SetPropertyValue<Estado>(nameof(IdEstado), ref fIdEstado, value); }
        }
        [Association(@"EntradaReferencesUsuario")]
        public XPCollection<Entrada> Entradas { get { return GetCollection<Entrada>(nameof(Entradas)); } }
        [Association(@"VentaReferencesUsuario")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
