//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SFPanaderia.PanaderiaBD
{

    public partial class Venta : XPLiteObject
    {
        int fIdVenta;
        [Key(true)]
        [Persistent(@"idVenta")]
        public int IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<int>(nameof(IdVenta), ref fIdVenta, value); }
        }
        DateTime fFechaVenta;
        [Persistent(@"fechaVenta")]
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaVenta
        {
            get { return fFechaVenta; }
            set { SetPropertyValue<DateTime>(nameof(FechaVenta), ref fFechaVenta, value); }
        }
        int fCantidad;
        [Persistent(@"cantidad")]
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        double fDescuento;
        [Persistent(@"descuento")]
        public double Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<double>(nameof(Descuento), ref fDescuento, value); }
        }
        double fMontoFinal;
        [Persistent(@"montoFinal")]
        public double MontoFinal
        {
            get { return fMontoFinal; }
            set { SetPropertyValue<double>(nameof(MontoFinal), ref fMontoFinal, value); }
        }
        Empleado fIdEmpleado;
        [Persistent(@"idEmpleado")]
        [Association(@"VentaReferencesEmpleado")]
        public Empleado IdEmpleado
        {
            get { return fIdEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(IdEmpleado), ref fIdEmpleado, value); }
        }
        Cliente fIdCliente;
        [Persistent(@"idCliente")]
        [Association(@"VentaReferencesCliente")]
        public Cliente IdCliente
        {
            get { return fIdCliente; }
            set { SetPropertyValue<Cliente>(nameof(IdCliente), ref fIdCliente, value); }
        }
        [Association(@"DetalleVentaReferencesVenta")]
        public XPCollection<DetalleVenta> DetalleVentas { get { return GetCollection<DetalleVenta>(nameof(DetalleVentas)); } }
    }

}
